plugin1=co.edu.unicauca.microkernel.plugins.MultipleChoiceQuestionPlugin
plugin2=co.edu.unicauca.microkernel.plugins.CaseQuestionPlugin
plugin3=co.edu.unicauca.microkernel.plugins.MultimediaQuestionPlugin